<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250914152853 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE car (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, model INT NOT NULL, color VARCHAR(255) NOT NULL, relation VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE carparts (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, price INT NOT NULL, car_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FF0FC349C3C6F69F ON carparts (car_id)');
        $this->addSql('CREATE TABLE dragon_treasure (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description VARCHAR(255) NOT NULL, value INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE carparts ADD CONSTRAINT FK_FF0FC349C3C6F69F FOREIGN KEY (car_id) REFERENCES car (id)');
        $this->addSql('ALTER TABLE job_task ADD admin_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE job_task ADD CONSTRAINT FK_D5B2AD64642B8210 FOREIGN KEY (admin_id) REFERENCES "users" (id)');
        $this->addSql('CREATE INDEX IDX_D5B2AD64642B8210 ON job_task (admin_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE carparts DROP CONSTRAINT FK_FF0FC349C3C6F69F');
        $this->addSql('DROP TABLE car');
        $this->addSql('DROP TABLE carparts');
        $this->addSql('DROP TABLE dragon_treasure');
        $this->addSql('ALTER TABLE job_task DROP CONSTRAINT FK_D5B2AD64642B8210');
        $this->addSql('DROP INDEX IDX_D5B2AD64642B8210');
        $this->addSql('ALTER TABLE job_task DROP admin_id');
    }
}
